/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PreprocessFunction } from "./PreprocessFunction";
import { PreprocessFunctionCountArgs } from "./PreprocessFunctionCountArgs";
import { PreprocessFunctionFindManyArgs } from "./PreprocessFunctionFindManyArgs";
import { PreprocessFunctionFindUniqueArgs } from "./PreprocessFunctionFindUniqueArgs";
import { DeletePreprocessFunctionArgs } from "./DeletePreprocessFunctionArgs";
import { PreprocessFunctionService } from "../preprocessFunction.service";
@graphql.Resolver(() => PreprocessFunction)
export class PreprocessFunctionResolverBase {
  constructor(protected readonly service: PreprocessFunctionService) {}

  async _preprocessFunctionsMeta(
    @graphql.Args() args: PreprocessFunctionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PreprocessFunction])
  async preprocessFunctions(
    @graphql.Args() args: PreprocessFunctionFindManyArgs
  ): Promise<PreprocessFunction[]> {
    return this.service.preprocessFunctions(args);
  }

  @graphql.Query(() => PreprocessFunction, { nullable: true })
  async preprocessFunction(
    @graphql.Args() args: PreprocessFunctionFindUniqueArgs
  ): Promise<PreprocessFunction | null> {
    const result = await this.service.preprocessFunction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PreprocessFunction)
  async deletePreprocessFunction(
    @graphql.Args() args: DeletePreprocessFunctionArgs
  ): Promise<PreprocessFunction | null> {
    try {
      return await this.service.deletePreprocessFunction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
